kind: pipeline
type: docker
name: pygoodwe

steps:
- name: testbuild
  image: python:3.7
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  - pipenv run python setup.py sdist bdist_wheel 
